# Generated by Django 4.1.4 on 2022-12-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("profile", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=500)),
                ("phone", models.CharField(max_length=500)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=500)),
                ("subject", models.CharField(max_length=500)),
                ("message", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="image/")),
                ("type", models.CharField(max_length=500)),
                ("date", models.DateField()),
            ],
        ),
    ]
